# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
      - '5432-5432'
    restart: always
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080